import type { ConversionProfile } from '../types';

const source = { action: 'source' as const };

export const defaultProfile: ConversionProfile = {
  profile_name: 'Padrão BA Prestados',
  output_layout: 'ba_prestados',
  cod_prosoft: '0001',
  especie_documento: 'NFSE',
  modelo_nf: 'OU000',
  tipo_documento: '001',
  situacao_documento: '',
  cfps: '',
  cod_receita_irrf: '',
  cod_rec_pis: '',
  cod_rec_cofins: '',
  responsavel_retencao: '0',
  tipo_recolhimento: '',
  motivo_retencao: '',
  operacao_nota: '',
  cst_pis: '',
  cst_cofins: '',
  cst_iss: '',
  obs_extended: 'auto',
  field_rules: {
    base_calculo: source,
    iss_aliquota: source,
    iss_devido: source,
    iss_retido: source,
    valor_iss: source,
    valor_liquido: source,
    valor_irrf: source,
    valor_inss: source,
    valor_pis: source,
    valor_cofins: source,
    valor_csll: source,
    descontos: source,
    deducoes: source,
    observacao: source,
    codigo_servico: source,
    municipio: source,
    serie: source,
    numero: source,
    data_emissao: source,
    data_competencia: source,
    tipo_documento: source,
    especie_documento: source,
    natureza_operacao: source,
    campos_complementares: source,
  },
};
