import type { ConversionProfile } from '../types';

export const defaultProfile: ConversionProfile = {
  profile_name: 'Padrão BA Prestados',
  output_layout: 'ba_prestados',
  cod_prosoft: '0001',
  especie_documento: 'NFSE',
  modelo_nf: 'OU000',
  tipo_documento: '001',
  situacao_documento: '',
  cfps: '',
  cod_receita_irrf: '',
  cod_rec_pis: '',
  cod_rec_cofins: '',
  responsavel_retencao: '0',
  tipo_recolhimento: '',
  motivo_retencao: '',
  operacao_nota: '',
  cst_pis: '',
  cst_cofins: '',
  cst_iss: '',
  obs_extended: 'auto',
  field_rules: {
    base_calculo: { action: 'source' },
    iss_aliquota: { action: 'source' },
    iss_devido: { action: 'source' },
    iss_retido: { action: 'source' },
    valor_liquido: { action: 'source' },
    valor_irrf: { action: 'source' },
    valor_inss: { action: 'source' },
    valor_pis: { action: 'source' },
    valor_cofins: { action: 'source' },
    valor_csll: { action: 'source' },
    observacao: { action: 'source' },
    codigo_servico: { action: 'source' },
  },
};
